<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-06T19:32:52 IST" name="Default suite" finished-at="2025-01-06T19:32:55 IST" duration-ms="3652">
    <groups>
    </groups>
    <test started-at="2025-01-06T19:32:52 IST" name="Default test" finished-at="2025-01-06T19:32:55 IST" duration-ms="3652">
      <class name="com.qa.qaassessment.tests.QuestionSettingsPageTest">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String)[pri:0, instance:com.qa.qaassessment.tests.QuestionSettingsPageTest@19e4653c]" started-at="2025-01-06T19:32:52 IST" name="setUp" finished-at="2025-01-06T19:32:55 IST" duration-ms="3109" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://qa-assesments.unstop.events.s3-website.ap-south-1.amazonaws.com/basic]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="basicPageTitleTest()[pri:0, instance:com.qa.qaassessment.tests.QuestionSettingsPageTest@19e4653c]" started-at="2025-01-06T19:32:55 IST" name="basicPageTitleTest" finished-at="2025-01-06T19:32:55 IST" duration-ms="51" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Unstop - Competitions, Quizzes, Hackathons, Scholarships and Internships for Students and Corporates] but found [403 Forbidden]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Unstop - Competitions, Quizzes, Hackathons, Scholarships and Internships for Students and Corporates] but found [403 Forbidden]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.qaassessment.tests.QuestionSettingsPageTest.basicPageTitleTest(QuestionSettingsPageTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.qaassessment.tests.QuestionSettingsPageTest@19e4653c]" started-at="2025-01-06T19:32:55 IST" name="tearDown" finished-at="2025-01-06T19:32:55 IST" duration-ms="382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.qaassessment.tests.QuestionSettingsPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
